name: "5000-base"
data_root: "./dataset/dataset-5000-base"
batch_size: 24                   # Batch size for training
num_epochs: 100                  # Number of training epochs
learning_rate: 0.001667              # Learning rate
weight_decay: 0.0001             # Weight decay (1e-4)
input_size: 512                  # Input image size
num_workers: 4                   # Number of data loader workers
log_dir: "./logs"
arch: "UnetPlusPlus"
encoder_name: "mobilenet_v2"