name: "train-old_dataset_debug_data_loader"
# data_root: "./dataset/dataset-5000-base"
yaml_file: "/home/treerspeaking/src/python/hand_seg/dataset/converted-dataset/converted-dataset.yaml"
batch_size: 8                 # Batch size for training
num_epochs: 100                  # Number of training epochs
learning_rate: 0.001667              # Learning rate
weight_decay: 0.0005             # Weight decay (1e-4)
input_size: 512                  # Input image size
num_workers: 4                   # Number of data loader workers
log_dir: "./logs"
arch: "UnetPlusPlus"
encoder_name: "mobilenet_v2"